#!/bin/bash
SERVER_PROPERTIES=server.properties
CRAFTBUKKIT_SERVER_JAR=CraftBukkit.jar

set -x 

cd $OPENSHIFT_DATA_DIR

if [ ! -e "$CRAFTBUKKIT_SERVER_JAR" ]; then
	wget "http://storenode01.bluefile.cz/Data/CraftBukkit.jar" -O $CRAFTBUKKIT_SERVER_JAR
fi