#!/bin/bash
SERVER_PROPERTIES=server.properties
CRAFTBUKKIT_SERVER_JAR=craftbukkit-dev.jar

set -x 

cd $OPENSHIFT_DATA_DIR

if [ ! -e "$CRAFTBUKKIT_SERVER_JAR" ]; then
	wget "https://ci.techcable.net/job/TacoSpigot/49/artifact/build/TacoSpigot.jar" -O $CRAFTBUKKIT_SERVER_JAR
fi

